project:
  type: website
  output-dir: docs

website:
  title: "Summer School 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - umsetzung.qmd
      - about.qmd
    logo: logo_iot.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
editor: visual

